name: ci

on:
  push:
    branches: main
  pull_request:

env:
  TEST_TAG: ${{ github.repository }}:test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: E2E Test
        run: |
          docker run -d -p 127.0.0.1:3000:3000 -p [::1]:3000:3000 --rm --env ZAPPER_API_KEY=${{ secrets.ZAPPER_API_KEY }} ${{ env.TEST_TAG }}
          yarn
          yarn test:e2e
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
      - name: Image digest
        if: github.ref == 'refs/heads/main'
        run: echo ${{ steps.docker_build.outputs.digest }}
