name: ci

on:
  push:
    branches: test-run-e2e

env:
  TEST_TAG: ${{ github.repository }}:test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          # context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: E2E Test
        run: |
          docker run -d --rm --env ZAPPER_API_KEY=${{ secrets.ZAPPER_API_KEY }} ${{ env.TEST_TAG }}
          yarn
          yarn test:e2e
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     # platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ github.repository }}:latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
